### Association Analysis - Basics
There are a couple of terms used in association analysis that are important to understand. This chapter in Introduction to Data Mining is a great reference for those interested in the math behind these definitions and the details of the algorithm implementation.

Association rules are normally written like this: {Diapers} -> {Beer} which means that there is a strong relationship between customers that purchased diapers and also purchased beer in the same transaction.

In the above example, the {Diaper} is the antecedent and the {Beer} is the consequent. Both antecedents and consequents can have multiple items. In other words, {Diaper, Gum} -> {Beer, Chips} is a valid rule.

#### Support
Support is the relative frequency that the rules show up. In many instances, you may want to look for high support in order to make sure it is a useful relationship. However, there may be instances where a low support is useful if you are trying to find “hidden” relationships.

#### Confidence
Confidence is a measure of the reliability of the rule. A confidence of .5 in the above example would mean that in 50% of the cases where Diaper and Gum were purchased, the purchase also included Beer and Chips. For product recommendation, a 50% confidence may be perfectly acceptable but in a medical situation, this level may not be high enough.

#### Lift
Lift is the ratio of the observed support to that expected if the two rules were independent (see wikipedia). The basic rule of thumb is that a lift value close to 1 means the rules were completely independent. Lift values > 1 are generally more “interesting” and could be indicative of a useful rule pattern.

In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\sneha\anaconda3\lib\site-packages (0.24.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\sneha\anaconda3\lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\sneha\anaconda3\lib\site-packages (from mlxtend) (2.4.4)
Requirement already satisfied: pandas>=2.3.3 in c:\users\sneha\anaconda3\lib\site-packages (from mlxtend) (3.0.2)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\sneha\anaconda3\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\sneha\anaconda3\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\users\sneha\anaconda3\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sneha\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sneha\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sneha\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\sneha\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
df = pd.read_excel(r'C:\Users\sneha\anaconda assignment\excel\Online Retail - 1774769511056.xlsx')

In [4]:
df.Country.value_counts()

Country
Germany      9495
France       8557
Australia    1259
USA           291
Singapore     229
Canada        151
Name: count, dtype: int64

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
1,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
2,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
3,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
4,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France

In [6]:
# Clean up spaces in description and remove any rows that don't have a valid invoice
df['Description'] = df['Description'].str.strip()
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
1,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
2,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
3,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
4,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19982 entries, 0 to 19981
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    19982 non-null  object
 1   StockCode    19982 non-null  object
 2   Description  19982 non-null  str
 3   Quantity     19982 non-null  int64
 4   InvoiceDate  19982 non-null  datetime64[us]
 5   UnitPrice    19982 non-null  float64
 6   CustomerID   19916 non-null  float64
 7   Country      19982 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(2), str(2)
memory usage: 1.8+ MB

In [9]:
#Drop the rows that don’t have invoice numbers and remove the credit transactions (those with invoice numbers containing C).
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 19187 entries, 0 to 19981
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    19187 non-null  str
 1   StockCode    19187 non-null  object
 2   Description  19187 non-null  str
 3   Quantity     19187 non-null  int64
 4   InvoiceDate  19187 non-null  datetime64[us]
 5   UnitPrice    19187 non-null  float64
 6   CustomerID   19121 non-null  float64
 7   Country      19187 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(3)
memory usage: 2.0+ MB

In [11]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
1,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
2,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
3,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
4,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France

In [15]:
'''df.dropna(subset=['InvoiceNo','Description','Quantity'],inplace=True)'''

In [16]:
'''
basket1 = (df[df['Country'] =="France"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack(fill_value=0))
'''

In [17]:
'''basket1'''

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
'''
basket2 = (df[df['Country']=='France'].pivot_table(index='InvoiceNo',
                                                   columns='Description',
                                                   values='Quantity',
                                                   aggfunc='sum',
                                                   fill_value=0))

'''

"\nbasket2 = (df[df['Country']=='France'].pivot_table(index='InvoiceNo',\n                                                   columns='Description',\n                                                   values='Quantity',\n                                                   aggfunc='sum',\n                                                   fill_value=0))\n\n"

In [61]:
basket2

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
#To keeping data set is small, Filtering the data for only one country - France
basket = (df[df['Country'] =="France"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

In [36]:
basket

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581279,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
#we need to consolidate the items into 1 transaction per row with each product 1 hot encoded.
# Convert the units to 1 hot encoded values
def encode_units(x):
    if x <= 0:
        return 0
    else:
        return 1

In [42]:
basket_sets = basket.map(encode_units)

In [43]:
basket_sets

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
# No need to track postage - It is not an item
basket_sets.drop('POSTAGE', inplace=True, axis=1)

In [48]:
# Build up the frequent items
#Now that the data is structured properly, we can generate frequent item sets that have a support of 
#at least 7% (this number was chosen so that I could get enough useful examples):
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)

C:\Users\sneha\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [49]:
frequent_itemsets

     support                                           itemsets
0   0.071429           frozenset({4 TRADITIONAL SPINNING TOPS})
1   0.096939            frozenset({ALARM CLOCK BAKELIKE GREEN})
2   0.102041             frozenset({ALARM CLOCK BAKELIKE PINK})
3   0.094388              frozenset({ALARM CLOCK BAKELIKE RED})
4   0.081633          frozenset({BAKING SET 9 PIECE RETROSPOT})
5   0.071429          frozenset({CHILDRENS CUTLERY DOLLY GIRL})
6   0.099490                  frozenset({DOLLY GIRL LUNCH BOX})
7   0.096939               frozenset({JUMBO BAG RED RETROSPOT})
8   0.076531            frozenset({JUMBO BAG WOODLAND ANIMALS})
9   0.125000                frozenset({LUNCH BAG APPLE DESIGN})
10  0.084184           frozenset({LUNCH BAG DOLLY GIRL DESIGN})
11  0.153061               frozenset({LUNCH BAG RED RETROSPOT})
12  0.119898             frozenset({LUNCH BAG SPACEBOY DESIGN})
13  0.117347                    frozenset({LUNCH BAG WOODLAND})
14  0.142857      frozenset({LUNCH BOX WITH CUTLERY RETROSPOT})
15  0.104592                frozenset({MINI PAINT SET VINTAGE})
16  0.102041       frozenset({PACK OF 72 RETROSPOT CAKE CASES})
17  0.081633               frozenset({PAPER BUNTING RETROSPOT})
18  0.168367         frozenset({PLASTERS IN TIN CIRCUS PARADE})
19  0.137755              frozenset({PLASTERS IN TIN SPACEBOY})
20  0.081633             frozenset({PLASTERS IN TIN STRONGMAN})
21  0.170918      frozenset({PLASTERS IN TIN WOODLAND ANIMALS})
22  0.188776                    frozenset({RABBIT NIGHT LIGHT})
23  0.096939           frozenset({RED RETROSPOT CHARLOTTE BAG})
24  0.137755              frozenset({RED RETROSPOT MINI CASES})
25  0.071429              frozenset({RED RETROSPOT PICNIC BAG})
26  0.181122         frozenset({RED TOADSTOOL LED NIGHT LIGHT})
27  0.125000              frozenset({REGENCY CAKESTAND 3 TIER})
28  0.086735       frozenset({RETROSPOT TEA SET CERAMIC 11 PC})
29  0.107143     frozenset({ROUND SNACK BOXES SET OF 4 FRUITS})
30  0.158163    frozenset({ROUND SNACK BOXES SET OF4 WOODLAND})
31  0.076531     frozenset({SET/10 RED POLKADOT PARTY CANDLES})
32  0.132653    frozenset({SET/20 RED RETROSPOT PAPER NAPKINS})
33  0.137755           frozenset({SET/6 RED SPOTTY PAPER CUPS})
34  0.127551         frozenset({SET/6 RED SPOTTY PAPER PLATES})
35  0.071429                frozenset({SPACEBOY BIRTHDAY CARD})
36  0.125000                    frozenset({SPACEBOY LUNCH BOX})
37  0.122449     frozenset({STRAWBERRY LUNCH BOX WITH CUTLERY})
38  0.094388               frozenset({TEA PARTY BIRTHDAY CARD})
39  0.073980                frozenset({WOODLAND CHARLOTTE BAG})
40  0.073980  frozenset({ALARM CLOCK BAKELIKE GREEN, ALARM C...
41  0.079082  frozenset({ALARM CLOCK BAKELIKE GREEN, ALARM C...
42  0.073980  frozenset({ALARM CLOCK BAKELIKE RED, ALARM CLO...
43  0.071429  frozenset({DOLLY GIRL LUNCH BOX, SPACEBOY LUNC...
44  0.089286  frozenset({PLASTERS IN TIN CIRCUS PARADE, PLAS...
45  0.102041  frozenset({PLASTERS IN TIN CIRCUS PARADE, PLAS...
46  0.104592  frozenset({PLASTERS IN TIN SPACEBOY, PLASTERS ...
47  0.102041  frozenset({SET/20 RED RETROSPOT PAPER NAPKINS,...
48  0.102041  frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...
49  0.122449  frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...
50  0.099490  frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...

In [51]:
frequent_itemsets.sort_values(by='support', ascending=False)

     support                                           itemsets
22  0.188776                    frozenset({RABBIT NIGHT LIGHT})
26  0.181122         frozenset({RED TOADSTOOL LED NIGHT LIGHT})
21  0.170918      frozenset({PLASTERS IN TIN WOODLAND ANIMALS})
18  0.168367         frozenset({PLASTERS IN TIN CIRCUS PARADE})
30  0.158163    frozenset({ROUND SNACK BOXES SET OF4 WOODLAND})
11  0.153061               frozenset({LUNCH BAG RED RETROSPOT})
14  0.142857      frozenset({LUNCH BOX WITH CUTLERY RETROSPOT})
19  0.137755              frozenset({PLASTERS IN TIN SPACEBOY})
33  0.137755           frozenset({SET/6 RED SPOTTY PAPER CUPS})
24  0.137755              frozenset({RED RETROSPOT MINI CASES})
32  0.132653    frozenset({SET/20 RED RETROSPOT PAPER NAPKINS})
34  0.127551         frozenset({SET/6 RED SPOTTY PAPER PLATES})
9   0.125000                frozenset({LUNCH BAG APPLE DESIGN})
27  0.125000              frozenset({REGENCY CAKESTAND 3 TIER})
36  0.125000                    frozenset({SPACEBOY LUNCH BOX})
37  0.122449     frozenset({STRAWBERRY LUNCH BOX WITH CUTLERY})
49  0.122449  frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...
12  0.119898             frozenset({LUNCH BAG SPACEBOY DESIGN})
13  0.117347                    frozenset({LUNCH BAG WOODLAND})
29  0.107143     frozenset({ROUND SNACK BOXES SET OF 4 FRUITS})
15  0.104592                frozenset({MINI PAINT SET VINTAGE})
46  0.104592  frozenset({PLASTERS IN TIN SPACEBOY, PLASTERS ...
2   0.102041             frozenset({ALARM CLOCK BAKELIKE PINK})
48  0.102041  frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...
47  0.102041  frozenset({SET/20 RED RETROSPOT PAPER NAPKINS,...
16  0.102041       frozenset({PACK OF 72 RETROSPOT CAKE CASES})
45  0.102041  frozenset({PLASTERS IN TIN CIRCUS PARADE, PLAS...
50  0.099490  frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...
6   0.099490                  frozenset({DOLLY GIRL LUNCH BOX})
1   0.096939            frozenset({ALARM CLOCK BAKELIKE GREEN})
23  0.096939           frozenset({RED RETROSPOT CHARLOTTE BAG})
7   0.096939               frozenset({JUMBO BAG RED RETROSPOT})
38  0.094388               frozenset({TEA PARTY BIRTHDAY CARD})
3   0.094388              frozenset({ALARM CLOCK BAKELIKE RED})
44  0.089286  frozenset({PLASTERS IN TIN CIRCUS PARADE, PLAS...
28  0.086735       frozenset({RETROSPOT TEA SET CERAMIC 11 PC})
10  0.084184           frozenset({LUNCH BAG DOLLY GIRL DESIGN})
4   0.081633          frozenset({BAKING SET 9 PIECE RETROSPOT})
17  0.081633               frozenset({PAPER BUNTING RETROSPOT})
20  0.081633             frozenset({PLASTERS IN TIN STRONGMAN})
41  0.079082  frozenset({ALARM CLOCK BAKELIKE GREEN, ALARM C...
8   0.076531            frozenset({JUMBO BAG WOODLAND ANIMALS})
31  0.076531     frozenset({SET/10 RED POLKADOT PARTY CANDLES})
42  0.073980  frozenset({ALARM CLOCK BAKELIKE RED, ALARM CLO...
40  0.073980  frozenset({ALARM CLOCK BAKELIKE GREEN, ALARM C...
39  0.073980                frozenset({WOODLAND CHARLOTTE BAG})
0   0.071429           frozenset({4 TRADITIONAL SPINNING TOPS})
5   0.071429          frozenset({CHILDRENS CUTLERY DOLLY GIRL})
25  0.071429              frozenset({RED RETROSPOT PICNIC BAG})
35  0.071429                frozenset({SPACEBOY BIRTHDAY CARD})
43  0.071429  frozenset({DOLLY GIRL LUNCH BOX, SPACEBOY LUNC...

In [52]:
#Generate the rules with their corresponding support, confidence and lift:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE PINK}),0.096939,0.102041,0.073980,0.763158,7.478947,1.0,0.064088,3.791383,0.959283,0.591837,0.736244,0.744079
1,frozenset({ALARM CLOCK BAKELIKE PINK}),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.102041,0.096939,0.073980,0.725000,7.478947,1.0,0.064088,3.283859,0.964734,0.591837,0.695480,0.744079
2,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE RED}),0.096939,0.094388,0.079082,0.815789,8.642959,1.0,0.069932,4.916181,0.979224,0.704545,0.796590,0.826814
3,frozenset({ALARM CLOCK BAKELIKE RED}),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.094388,0.096939,0.079082,0.837838,8.642959,1.0,0.069932,5.568878,0.976465,0.704545,0.820431,0.826814
4,frozenset({ALARM CLOCK BAKELIKE RED}),frozenset({ALARM CLOCK BAKELIKE PINK}),0.094388,0.102041,0.073980,0.783784,7.681081,1.0,0.064348,4.153061,0.960466,0.604167,0.759214,0.754392
5,frozenset({ALARM CLOCK BAKELIKE PINK}),frozenset({ALARM CLOCK BAKELIKE RED}),0.102041,0.094388,0.073980,0.725000,7.681081,1.0,0.064348,3.293135,0.968652,0.604167,0.696338,0.754392
6,frozenset({DOLLY GIRL LUNCH BOX}),frozenset({SPACEBOY LUNCH BOX}),0.099490,0.125000,0.071429,0.717949,5.743590,1.0,0.058992,3.102273,0.917139,0.466667,0.677656,0.644689
7,frozenset({SPACEBOY LUNCH BOX}),frozenset({DOLLY GIRL LUNCH BOX}),0.125000,0.099490,0.071429,0.571429,5.743590,1.0,0.058992,2.101190,0.943878,0.466667,0.524079,0.644689
8,frozenset({PLASTERS IN TIN CIRCUS PARADE}),frozenset({PLASTERS IN TIN SPACEBOY}),0.168367,0.137755,0.089286,0.530303,3.849607,1.0,0.066092,1.835747,0.890096,0.411765,0.455263,0.589226
9,frozenset({PLASTERS IN TIN SPACEBOY}),frozenset({PLASTERS IN TIN CIRCUS PARADE}),0.137755,0.168367,0.089286,0.648148,3.849607,1.0,0.066092,2.363588,0.858495,0.411765,0.576914,0.589226
10,frozenset({PLASTERS IN TIN CIRCUS PARADE}),frozenset({PLASTERS IN TIN WOODLAND ANIMALS}),0.168367,0.170918,0.102041,0.606061,3.545907,1.0,0.073264,2.104592,0.863344,0.430108,0.524848,0.601538
11,frozenset({PLASTERS IN TIN WOODLAND ANIMALS}),frozenset({PLASTERS IN TIN CIRCUS PARADE}),0.170918,0.168367,0.102041,0.597015,3.545907,1.0,0.073264,2.063681,0.866000,0.430108,0.515429,0.601538
12,frozenset({PLASTERS IN TIN SPACEBOY}),frozenset({PLASTERS IN TIN WOODLAND ANIMALS}),0.137755,0.170918,0.104592,0.759259,4.442233,1.0,0.081047,3.443878,0.898687,0.512500,0.709630,0.685600
13,frozenset({PLASTERS IN TIN WOODLAND ANIMALS}),frozenset({PLASTERS IN TIN SPACEBOY}),0.170918,0.137755,0.104592,0.611940,4.442233,1.0,0.081047,2.221939,0.934634,0.512500,0.549943,0.685600
14,frozenset({SET/20 RED RETROSPOT PAPER NAPKINS}),frozenset({SET/6 RED SPOTTY PAPER CUPS}),0.132653,0.137755,0.102041,0.769231,5.584046,1.0,0.083767,3.736395,0.946471,0.606061,0.732362,0.754986
15,frozenset({SET/6 RED SPOTTY PAPER CUPS}),frozenset({SET/20 RED RETROSPOT PAPER NAPKINS}),0.137755,0.132653,0.102041,0.740741,5.584046,1.0,0.083767,3.345481,0.952071,0.606061,0.701089,0.754986
16,frozenset({SET/6 RED SPOTTY PAPER PLATES}),frozenset({SET/20 RED RETROSPOT PAPER NAPKINS}),0.127551,0.132653,0.102041,0.800000,6.030769,1.0,0.085121,4.336735,0.956140,0.645161,0.769412,0.784615
17,frozenset({SET/20 RED RETROSPOT PAPER NAPKINS}),frozenset({SET/6 RED SPOTTY PAPER PLATES}),0.132653,0.127551,0.102041,0.769231,6.030769,1.0,0.085121,3.780612,0.961765,0.645161,0.735493,0.784615
18,frozenset({SET/6 RED SPOTTY PAPER PLATES}),frozenset({SET/6 RED SPOTTY PAPER CUPS}),0.127551,0.137755,0.122449,0.960000,6.968889,1.0,0.104878,21.556122,0.981725,0.857143,0.953609,0.924444
19,frozenset({SET/6 RED SPOTTY PAPER CUPS}),frozenset({SET/6 RED SPOTTY PAPER PLATES}),0.137755,0.127551,0.122449,0.888889,6.968889,1.0,0.104878,7.852041,0.993343,0.857143,0.872645,0.924444
20,"frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...",frozenset({SET/6 RED SPOTTY PAPER CUPS}),0.102041,0.137755,0.099490,0.975000,7.077778,1.0,0.085433,34.489796,0.956294,0.709091,0.971006,0.848611
21,"frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...",frozenset({SET/20 RED RETROSPOT PAPER NAPKINS}),0.122449,0.132653,0.099490,0.812500,6.125000,1.0,0.083247,4.625850,0.953488,0.639344,0.783824,0.781250
22,"frozenset({SET/20 RED RETROSPOT PAPER NAPKINS,...",frozenset({SET/6 RED SPOTTY PAPER PLATES}),0.102041,0.127551,0.099490,0.975000,7.644000,1.0,0.086474,34.897959,0.967949,0.764706,0.971345,0.877500
23,frozenset({SET/6 RED SPOTTY PAPER PLATES}),"frozenset({SET/20 RED RETROSPOT PAPER NAPKINS,...",0.127551,0.102041,0.099490,0.780000,7.644000,1.0,0.086474,4.081633,0.996251,0.764706,0.755000,0.877500
24,frozenset({SET/20 RED RETROSPOT PAPER NAPKINS}),"frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...",0.132653,0.122449,0.099490,0.750000,6.125000,1.0,0.083247,3.510204,0.964706,0.639344,0.715116,0.781250
25,frozenset({SET/6 RED SPOTTY PAPER CUPS}),"frozenset({SET/6 RED SPOTTY PAPER PLATES, SET/...",0.137755,0.102041,0.099490,0.722222,7.077778,1.0,0.085433,3.232653,0.995904,0.709091,0.690657,0.848611

In [53]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='str')

In [54]:
rules = rules[['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift']]

In [ ]:
rules.to_csv("C:/projects/jan_ml/data/output/associations.csv")

In [ ]:
# Did data preparation: apriori - combinations --- output-- association rules - support, lift and confidence

In [ ]:
# Colloborative Filtering - in Next weeks class
# User Based
# Item Based
# Model Based

# Euclidean,CosineSimilarity
# IForest
# Forecasting